Alterações para deixar as imagens do page-4 sincronizadas com o stora…
Brunopgm/admin-ong pull request #8
Opened 2020-10-28 02:44 UTC by Brunopgm

Sincronizei as imagens do page-4 com o storage e firestore

2020-10-28 22:24 UTC, tassioFront requested changes

2020-10-28 22:24 UTC, tassioFront commented on src/components/page-body/page-4/contact-logos.vue
> +const { mapGetters } = createNamespacedHelpers('page4')
🚀

2020-10-28 22:24 UTC, tassioFront commented on src/components/page-body/page-4/contact-logos.vue
> +        let contactIcons = null
```JS
const contactIcons = response.contactData.map(data => {
            this.cards[0].src = data.adressIcon
            this.cards[1].src = data.emailIcon
})
```

talvez nesse caso valia usa map. é bom explorar outros `array functions`

2020-10-28 22:24 UTC, tassioFront commented on src/components/page-body/page-4/contact-logos.vue
> +        this.$store.state.page4.readContactIcons = contactIcons
não é bom fazer isso. Alterar o estado só por `mutation`

2020-10-28 22:24 UTC, tassioFront commented on src/router/router.js
> +      name: "page4",
page4 faz sentido? acho qye deveria ter contexto. 👀

2020-10-29 01:31 UTC, Brunopgm commented on src/router/router.js
> +      name: "page4",
Boa

2020-10-29 01:33 UTC, Brunopgm commented on src/components/page-body/page-4/contact-logos.vue
> +        let contactIcons = null
Boa

2020-10-30 02:42 UTC, merged